# pg-tileserv Docker Compose example setup.
#
# To build/run, see README.md
#
version: "3"

services:
  pg_tileserv:
    image: scanlidocker/pg_tileserv_alpine3.12:v1

    container_name: pg_tileserv

    env_file:
      - pg_tileserv.env

    depends_on:
      - pg_tileserv_db

    ports:
      - 7800:7800

  pg_tileserv_db:
    image: nickblah/postgis:10.22-bullseye-postgis-3.2

    container_name: pg_tileserv_db

    volumes:
      - ./data:/work
      - pg_tileserv_db:/var/lib/postgresql/data

    env_file:
      - pg.env

volumes:
  pg_tileserv_db:
